package com.conversorAlura.co.frame;

import com.conversorAlura.co.libreria.realizarLlamadoPag;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author carolina
 */
public class BotonesIniciales extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public BotonesIniciales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        conversorMonedas = new javax.swing.JButton();
        conversorMedidas = new javax.swing.JButton();
        conversorVolumenes = new javax.swing.JButton();
        conversorTemperatura = new javax.swing.JButton();

        setToolTipText("");

        content.setMaximumSize(new java.awt.Dimension(600, 500));
        content.setMinimumSize(new java.awt.Dimension(600, 500));
        content.setPreferredSize(new java.awt.Dimension(600, 500));

        conversorMonedas.setText("Conversor Monedas");
        conversorMonedas.setMaximumSize(new java.awt.Dimension(180, 25));
        conversorMonedas.setMinimumSize(new java.awt.Dimension(180, 25));
        conversorMonedas.setPreferredSize(new java.awt.Dimension(180, 25));
        conversorMonedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversorMonedasMouseClicked(evt);
            }
        });
        conversorMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conversorMonedasActionPerformed(evt);
            }
        });

        conversorMedidas.setText("Conversor Medidas");
        conversorMedidas.setMaximumSize(new java.awt.Dimension(180, 25));
        conversorMedidas.setMinimumSize(new java.awt.Dimension(180, 25));
        conversorMedidas.setPreferredSize(new java.awt.Dimension(180, 25));
        conversorMedidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversorMedidasMouseClicked(evt);
            }
        });

        conversorVolumenes.setText("Conversor Volumenes");
        conversorVolumenes.setMaximumSize(new java.awt.Dimension(180, 25));
        conversorVolumenes.setMinimumSize(new java.awt.Dimension(180, 25));
        conversorVolumenes.setPreferredSize(new java.awt.Dimension(180, 25));
        conversorVolumenes.setRequestFocusEnabled(false);
        conversorVolumenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversorVolumenesMouseClicked(evt);
            }
        });

        conversorTemperatura.setText("Conversor Temperatura");
        conversorTemperatura.setMaximumSize(new java.awt.Dimension(180, 25));
        conversorTemperatura.setMinimumSize(new java.awt.Dimension(180, 25));
        conversorTemperatura.setPreferredSize(new java.awt.Dimension(180, 25));
        conversorTemperatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversorTemperaturaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conversorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conversorVolumenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conversorMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conversorMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(conversorMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(conversorMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(conversorVolumenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(conversorTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void conversorMonedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversorMonedasMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag1 = new realizarLlamadoPag();
        ConversorMoneda conv1 = new ConversorMoneda();
        Pag1.Llamado(conv1, content);
    }//GEN-LAST:event_conversorMonedasMouseClicked

    private void conversorMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conversorMonedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conversorMonedasActionPerformed

    private void conversorMedidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversorMedidasMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag2 = new realizarLlamadoPag();
        ConversorMedidas conv2 = new ConversorMedidas();
        Pag2.Llamado(conv2, content);
    }//GEN-LAST:event_conversorMedidasMouseClicked

    private void conversorVolumenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversorVolumenesMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag3 = new realizarLlamadoPag();
        ConversorVolumenes conv3 = new ConversorVolumenes();
        Pag3.Llamado(conv3, content);
    }//GEN-LAST:event_conversorVolumenesMouseClicked

    private void conversorTemperaturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversorTemperaturaMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag4 = new realizarLlamadoPag();
        ConversorTemperatura conv4 = new ConversorTemperatura();
        Pag4.Llamado(conv4, content);
    }//GEN-LAST:event_conversorTemperaturaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton conversorMedidas;
    private javax.swing.JButton conversorMonedas;
    private javax.swing.JButton conversorTemperatura;
    private javax.swing.JButton conversorVolumenes;
    // End of variables declaration//GEN-END:variables
}
