package com.conversorAlura.co.frame;

import com.conversorAlura.co.libreria.realizarLlamadoPag;


public class ConversorTemperatura extends javax.swing.JPanel {

    /**
     * Creates new form ConversorMoneda
     */
    public ConversorTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setLayout(null);

        content.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONVERSOR DE TEMPERATURA ALURA");
        content.add(jLabel1);
        jLabel1.setBounds(90, 50, 400, 21);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        content.add(jLabel2);
        jLabel2.setBounds(220, 120, 140, 100);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingrese al temperatura a convertir:");
        content.add(jLabel3);
        jLabel3.setBounds(190, 260, 205, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "K", "F" }));
        content.add(jComboBox1);
        jComboBox1.setBounds(90, 290, 72, 22);

        jButton1.setText("jButton1");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        content.add(jButton1);
        jButton1.setBounds(240, 290, 100, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "K", "F" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        content.add(jComboBox2);
        jComboBox2.setBounds(420, 290, 72, 22);

        jTextField1.setMaximumSize(new java.awt.Dimension(80, 22));
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 22));
        jTextField1.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextField1.setRequestFocusEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        content.add(jTextField1);
        jTextField1.setBounds(180, 290, 46, 22);

        jButton4.setText("Conversores");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        content.add(jButton4);
        jButton4.setBounds(6, 464, 120, 30);

        jTextField2.setMaximumSize(new java.awt.Dimension(80, 22));
        jTextField2.setMinimumSize(new java.awt.Dimension(80, 22));
        jTextField2.setPreferredSize(new java.awt.Dimension(80, 22));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        content.add(jTextField2);
        jTextField2.setBounds(360, 290, 46, 22);

        add(content);
        content.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag7 = new realizarLlamadoPag();
        BotonesIniciales conv7 = new BotonesIniciales();
        Pag7.Llamado(conv7, content);
    }//GEN-LAST:event_jButton4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
