package com.conversorAlura.co.frame;

import com.conversorAlura.co.libreria.UnidadesDeMedida;
import com.conversorAlura.co.libreria.UnidadesDeTemperatura;
import com.conversorAlura.co.libreria.realizarLlamadoPag;
import java.awt.Image;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class ConversorTemperatura extends javax.swing.JPanel {
    
    String tempSolve1;
    String tempSolve2;
    boolean validation = false; 
    /**
     * Creates new form ConversorMoneda
     */
    public ConversorTemperatura() {
        initComponents();
        setLabelImage(img, "/com/conversorAlura/co/img/temperatura.png");
        setButtonImage(changedButton, "/com/conversorAlura/co/img/flechas.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        boxMedidas1 = new javax.swing.JComboBox<>();
        boxMedidas2 = new javax.swing.JComboBox<>();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        changedButton = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        conversores = new javax.swing.JButton();

        setLayout(null);

        content.setLayout(null);

        tittle.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("CONVERSOR DE TEMPERATURA ALURA");
        content.add(tittle);
        tittle.setBounds(90, 50, 400, 21);

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        content.add(img);
        img.setBounds(220, 120, 140, 100);

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Ingrese al temperatura a convertir:");
        content.add(text);
        text.setBounds(190, 250, 205, 16);

        boxMedidas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "K", "F" }));
        content.add(boxMedidas1);
        boxMedidas1.setBounds(90, 290, 72, 22);

        boxMedidas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "K", "F" }));
        boxMedidas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMedidas2ActionPerformed(evt);
            }
        });
        content.add(boxMedidas2);
        boxMedidas2.setBounds(420, 290, 72, 22);

        textField1.setMaximumSize(new java.awt.Dimension(80, 22));
        textField1.setMinimumSize(new java.awt.Dimension(80, 22));
        textField1.setPreferredSize(new java.awt.Dimension(80, 22));
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });
        content.add(textField1);
        textField1.setBounds(180, 290, 46, 22);

        textField2.setMaximumSize(new java.awt.Dimension(80, 22));
        textField2.setMinimumSize(new java.awt.Dimension(80, 22));
        textField2.setPreferredSize(new java.awt.Dimension(80, 22));
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        textField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField2KeyTyped(evt);
            }
        });
        content.add(textField2);
        textField2.setBounds(360, 290, 46, 22);

        changedButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changedButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        changedButton.setInheritsPopupMenu(true);
        changedButton.setPreferredSize(new java.awt.Dimension(80, 23));
        changedButton.setRequestFocusEnabled(false);
        changedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changedButtonMouseClicked(evt);
            }
        });
        changedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changedButtonActionPerformed(evt);
            }
        });
        content.add(changedButton);
        changedButton.setBounds(260, 280, 60, 50);

        convertirButton.setText("Convertir");
        convertirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertirButtonMouseClicked(evt);
            }
        });
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });
        content.add(convertirButton);
        convertirButton.setBounds(220, 380, 140, 23);

        conversores.setText("Conversores");
        conversores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversoresMouseClicked(evt);
            }
        });
        content.add(conversores);
        conversores.setBounds(6, 464, 120, 30);

        add(content);
        content.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void changedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changedButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changedButtonActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void boxMedidas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMedidas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMedidas2ActionPerformed

    private void conversoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversoresMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag7 = new realizarLlamadoPag();
        BotonesIniciales conv7 = new BotonesIniciales();
        Pag7.Llamado(conv7, content);
    }//GEN-LAST:event_conversoresMouseClicked

    private void convertirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirButtonMouseClicked
        // TODO add your handling code here:int selectedDivisa1Index = listaDivisa1.getSelectedIndex();
        if (!textField2.getText().equals("") || !textField1.getText().equals("")){
                if (!textField2.getText().equals("") && !textField1.getText().equals("")) {
                return;}
                else if (!textField2.getText().equals("")) {
                    operando(textField2);
                }
                else if (!textField1.getText().equals("")) {
                    operando(textField1);
                }
             
             }
    }//GEN-LAST:event_convertirButtonMouseClicked

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void changedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changedButtonMouseClicked
        // TODO add your handling code here:
         
            try {
               
            if (textField1.getText().isEmpty() && textField2.getText().isEmpty() && validation){
                textField2.setText(tempSolve2);
                textField1.setText(tempSolve1);
                tempSolve1 = textField2.getText();
                tempSolve2 = textField1.getText();
            } 
             
              int selectedDivisa1Index = boxMedidas1.getSelectedIndex();
              int selectedDivisa2Index = boxMedidas2.getSelectedIndex();
              
              boxMedidas1.setSelectedIndex(selectedDivisa2Index);
              boxMedidas2.setSelectedIndex(selectedDivisa1Index);
              
              String savedResultadoLabel1 = textField2.getText();
              String savedResultadoLabel2 = textField1.getText();
              
              if (!textField2.getText().isEmpty()){
              
                textField2.setText(savedResultadoLabel2);
                textField1.setText(savedResultadoLabel1);

                textField2.revalidate();
                textField2.repaint();

                textField1.revalidate();
                textField1.repaint();
              }
             } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }
    }//GEN-LAST:event_changedButtonMouseClicked

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        // TODO add your handling code here:
         textField2.setText("");
    }//GEN-LAST:event_textField1KeyTyped

    private void textField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField2KeyTyped
        // TODO add your handling code here:
         textField1.setText("");
    }//GEN-LAST:event_textField2KeyTyped

    private void operando (JTextField valorBox) {
             String selectedMedida1Index = (String) boxMedidas1.getSelectedItem();
              String selectedMedida2Index = (String) boxMedidas2.getSelectedItem();
              

              // Realizar la conversión y asignar el resultado al JLabel de resultados
              
              try{
              UnidadesDeTemperatura valoresFinales = new UnidadesDeTemperatura();
              double valorOperacion1 = valoresFinales.operar(selectedMedida1Index, selectedMedida2Index, valorBox.getText());
              double valorOperacion2 = valoresFinales.operar(selectedMedida1Index, selectedMedida2Index, "1");
              BigDecimal bd1 = new BigDecimal(valorOperacion1);
              BigDecimal bd2 = new BigDecimal(valorOperacion2);
              bd1 = bd1.setScale(4, RoundingMode.HALF_UP);
              bd2 = bd2.setScale(4, RoundingMode.HALF_UP);
              double numeroRedondeado1 = bd1.doubleValue();
              double numeroRedondeado2 = bd2.doubleValue();
              String valorOperacion1String = Double.toString(numeroRedondeado1);
              String valorOperacion2String = Double.toString(numeroRedondeado2);
              if (valorBox == textField2){
              
              textField1.setText(valorOperacion1String);
              }else if (valorBox == textField1){textField2.setText(valorOperacion1String);}
              tempSolve1 = textField1.getText();
              tempSolve2 = textField2.getText();
              validation = true;
                 } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }
};

    private void setLabelImage (JLabel label1, String root){
    Icon icon = new ImageIcon(new ImageIcon(getClass().getResource(root)).getImage().getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH));
    label1.setIcon(icon);
    this.repaint();
    }
    
    private void setButtonImage (JButton buttonImage, String root){
    Icon icon = new ImageIcon(new ImageIcon(getClass().getResource(root)).getImage().getScaledInstance(buttonImage.getWidth(), buttonImage.getHeight(), Image.SCALE_SMOOTH));
    buttonImage.setIcon(icon);
    this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMedidas1;
    private javax.swing.JComboBox<String> boxMedidas2;
    private javax.swing.JButton changedButton;
    private javax.swing.JPanel content;
    private javax.swing.JButton conversores;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel img;
    private javax.swing.JLabel text;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
