package com.conversorAlura.co.frame;

import com.conversorAlura.co.libreria.UnidadesDeVolumen;
import com.conversorAlura.co.libreria.realizarLlamadoPag;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author carolina
 */
public class ConversorVolumenes extends javax.swing.JPanel {
    String tempSolve1;
    String tempSolve2;
    boolean validation = false; 
    /**
     * Creates new form ConversorMoneda
     */
    public ConversorVolumenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        boxMedidas1 = new javax.swing.JComboBox<>();
        boxMedidas2 = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        conversores = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setLayout(null);

        content.setLayout(null);

        tittle.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle.setText("CONVERSOR DE VOLUMENES ALURA");
        content.add(tittle);
        tittle.setBounds(100, 50, 388, 20);

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("jLabel2");
        content.add(img);
        img.setBounds(240, 80, 120, 90);

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Ingrese los volumenes a convertir:");
        content.add(text);
        text.setBounds(200, 200, 205, 16);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });
        content.add(textField1);
        textField1.setBounds(190, 240, 50, 22);

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        textField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField2KeyTyped(evt);
            }
        });
        content.add(textField2);
        textField2.setBounds(350, 240, 50, 22);

        boxMedidas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mL", "cm³", "L", "dm³", "m³", "gal", "dam³", "hm³", "km³", "g", "kg", "lb" }));
        content.add(boxMedidas1);
        boxMedidas1.setBounds(110, 240, 72, 22);

        boxMedidas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mL", "cm³", "L", "dm³", "m³", "gal", "dam³", "hm³", "km³", "g", "kg", "lb" }));
        content.add(boxMedidas2);
        boxMedidas2.setBounds(410, 240, 72, 22);

        changeButton.setText("jButton1");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        content.add(changeButton);
        changeButton.setBounds(250, 240, 90, 23);

        convertirButton.setText("Convertir");
        convertirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertirButtonMouseClicked(evt);
            }
        });
        content.add(convertirButton);
        convertirButton.setBounds(240, 290, 110, 23);

        conversores.setText("Conversores");
        conversores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conversoresMouseClicked(evt);
            }
        });
        content.add(conversores);
        conversores.setBounds(10, 463, 110, 30);

        add(content);
        content.setBounds(0, 0, 600, 500);

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeButtonActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void conversoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conversoresMouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag8 = new realizarLlamadoPag();
        BotonesIniciales conv8 = new BotonesIniciales();
        Pag8.Llamado(conv8, content);
    }//GEN-LAST:event_conversoresMouseClicked

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        // TODO add your handling code here:
          try {
               
            if (textField1.getText().isEmpty() && textField2.getText().isEmpty() && validation){
                textField2.setText(tempSolve2);
                textField1.setText(tempSolve1);
                tempSolve1 = textField2.getText();
                tempSolve2 = textField1.getText();
            } 
             
              int selectedDivisa1Index = boxMedidas1.getSelectedIndex();
              int selectedDivisa2Index = boxMedidas2.getSelectedIndex();
              
              boxMedidas1.setSelectedIndex(selectedDivisa2Index);
              boxMedidas2.setSelectedIndex(selectedDivisa1Index);
              
              String savedResultadoLabel1 = textField2.getText();
              String savedResultadoLabel2 = textField1.getText();
              
              if (!textField2.getText().isEmpty()){
              
                textField2.setText(savedResultadoLabel2);
                textField1.setText(savedResultadoLabel1);

                textField2.revalidate();
                textField2.repaint();

                textField1.revalidate();
                textField1.repaint();
              }
             } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }
    }//GEN-LAST:event_changeButtonMouseClicked

    private void convertirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirButtonMouseClicked
        // TODO add your handling code here:
           if (!textField2.getText().equals("") || !textField1.getText().equals("")){
                if (!textField2.getText().equals("") && !textField1.getText().equals("")) {
                return;}
                else if (!textField2.getText().equals("")) {
                    operando(textField2);
                }
                else if (!textField1.getText().equals("")) {
                    operando(textField1);
                }
             
             }
    }//GEN-LAST:event_convertirButtonMouseClicked

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        // TODO add your handling code here:
           textField2.setText("");
    }//GEN-LAST:event_textField1KeyTyped

    private void textField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField2KeyTyped
        // TODO add your handling code here:
          textField1.setText("");
    }//GEN-LAST:event_textField2KeyTyped

    
private void operando (JTextField valorBox) {
              String selectedMedida1Index = (String) boxMedidas1.getSelectedItem();
              String selectedMedida2Index = (String) boxMedidas2.getSelectedItem();
              

              // Realizar la conversión y asignar el resultado al JLabel de resultados
              
              try{
              UnidadesDeVolumen valoresFinales = new UnidadesDeVolumen();
              double valorOperacion1 = valoresFinales.operar(selectedMedida1Index, selectedMedida2Index, valorBox.getText());
              double valorOperacion2 = valoresFinales.operar(selectedMedida1Index, selectedMedida2Index, "1");
              BigDecimal bd1 = new BigDecimal(valorOperacion1);
              BigDecimal bd2 = new BigDecimal(valorOperacion2);
              bd1 = bd1.setScale(4, RoundingMode.HALF_UP);
              bd2 = bd2.setScale(4, RoundingMode.HALF_UP);
              double numeroRedondeado1 = bd1.doubleValue();
              double numeroRedondeado2 = bd2.doubleValue();
              String valorOperacion1String = Double.toString(numeroRedondeado1);
              String valorOperacion2String = Double.toString(numeroRedondeado2);
              if (valorBox == textField2){
              
              textField1.setText(valorOperacion1String);
              }else if (valorBox == textField1){textField2.setText(valorOperacion1String);}
              tempSolve1 = textField1.getText();
              tempSolve2 = textField2.getText();
              validation = true;
                 } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }
};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMedidas1;
    private javax.swing.JComboBox<String> boxMedidas2;
    private javax.swing.JButton changeButton;
    private javax.swing.JPanel content;
    private javax.swing.JButton conversores;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel text;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
