package com.conversorAlura.co.frame;


import com.conversorAlura.co.libreria.realizarLlamadoPag;
import com.conversorAlura.co.libreria.UnidadesDeMedida;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author carolina
 */
public class ConversorMedidas extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public ConversorMedidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        resultadoLabel1 = new javax.swing.JTextField();
        listaDivisa1 = new javax.swing.JComboBox<>();
        listaDivisa2 = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        convertirButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(null);

        content.setLayout(null);

        tittle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tittle.setText("CONVERSOR DE MEDIDAS ALURA");
        content.add(tittle);
        tittle.setBounds(140, 32, 303, 30);

        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img.setText("jLabel2");
        content.add(img);
        img.setBounds(210, 77, 160, 120);

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Ingrese las medidas a convertir:");
        content.add(text);
        text.setBounds(160, 210, 280, 20);

        valor.setMaximumSize(new java.awt.Dimension(64, 22));
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        content.add(valor);
        valor.setBounds(160, 250, 64, 22);

        resultadoLabel1.setMaximumSize(new java.awt.Dimension(64, 22));
        resultadoLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoLabel1ActionPerformed(evt);
            }
        });
        content.add(resultadoLabel1);
        resultadoLabel1.setBounds(370, 250, 64, 22);

        listaDivisa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "m", "km", "in", "yd", "mi" }));
        content.add(listaDivisa1);
        listaDivisa1.setBounds(70, 250, 81, 22);

        listaDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "m", "km", "in", "yd", "mi" }));
        content.add(listaDivisa2);
        listaDivisa2.setBounds(440, 250, 81, 22);

        changeButton.setText("jButton1");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        content.add(changeButton);
        changeButton.setBounds(230, 240, 131, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Equivalencia:");
        content.add(jLabel4);
        jLabel4.setBounds(230, 340, 131, 16);

        jButton3.setText("Conversores");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3);
        jButton3.setBounds(10, 460, 110, 30);

        convertirButton.setText("Convertir");
        convertirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convertirButtonMouseClicked(evt);
            }
        });
        convertirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirButtonActionPerformed(evt);
            }
        });
        content.add(convertirButton);
        convertirButton.setBounds(230, 300, 131, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        content.add(jPanel2);
        jPanel2.setBounds(210, 380, 168, 28);

        add(content);
        content.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoLabel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoLabel1ActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag6 = new realizarLlamadoPag();
        BotonesIniciales conv6 = new BotonesIniciales();
        Pag6.Llamado(conv6, content);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void convertirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertirButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeButtonActionPerformed

    private void convertirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirButtonMouseClicked
        // TODO add your handling code here:int selectedDivisa1Index = listaDivisa1.getSelectedIndex();
             if (!resultadoLabel1.getText().equals("") || !valor.getText().equals("")){
                if (!resultadoLabel1.getText().equals("") && !valor.getText().equals("")) {
                return;}
                else if (!resultadoLabel1.getText().equals("")) {
                    operando(resultadoLabel1);
                }
                else if (!valor.getText().equals("")) {
                    operando(valor);
                }
             
             };
              
        
              
              /*try{
              valorIngresado = valor.getText();
              double valorIngresadoDouble = Double.parseDouble(valorIngresado);
              double cambio =  Double.parseDouble(valorExchange1);
              String resultado = valoresFinales.resultadoConversion(valorIngresadoDouble, cambio);
              resultadoLabel2.setText(resultado);
               } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }*/
    }//GEN-LAST:event_convertirButtonMouseClicked

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        // TODO add your handling code here:
              int selectedDivisa1Index = listaDivisa1.getSelectedIndex();
              int selectedDivisa2Index = listaDivisa2.getSelectedIndex();
              
              listaDivisa1.setSelectedIndex(selectedDivisa2Index);
              listaDivisa2.setSelectedIndex(selectedDivisa1Index);
              
              String savedResultadoLabel1 = resultadoLabel1.getText();
              String savedResultadoLabel2 = valor.getText();
              double validationLabell = Double.parseDouble(savedResultadoLabel1);
              
              if (validationLabell != 0){
                resultadoLabel1.setText(savedResultadoLabel2);
                valor.setText(savedResultadoLabel1);
                
                resultadoLabel1.revalidate();
                resultadoLabel1.repaint();
        
                valor.revalidate();
                valor.repaint();
              }
    }//GEN-LAST:event_changeButtonMouseClicked

private void operando (JTextField valorBox) {
              String selectedDivisa1Index = (String) listaDivisa1.getSelectedItem();
              String selectedDivisa2Index = (String) listaDivisa2.getSelectedItem();
              

              // Realizar la conversión y asignar el resultado al JLabel de resultados
              
              try{UnidadesDeMedida valoresFinales = new UnidadesDeMedida();
              double valorExchange1 = valoresFinales.operar(selectedDivisa1Index, selectedDivisa2Index, valorBox.getText());
              BigDecimal bd = new BigDecimal(valorExchange1);
              bd = bd.setScale(3, RoundingMode.HALF_UP);
              double numeroRedondeado = bd.doubleValue();
              String valorExchangeString = Double.toString(numeroRedondeado);
              if (valorBox == resultadoLabel1){
              valor.setText(valorExchangeString);
              }else if (valorBox == valor){resultadoLabel1.setText(valorExchangeString);}
              
                } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
              }
};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JPanel content;
    private javax.swing.JButton convertirButton;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> listaDivisa1;
    private javax.swing.JComboBox<String> listaDivisa2;
    private javax.swing.JTextField resultadoLabel1;
    private javax.swing.JLabel text;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
