package com.conversorAlura.co.frame;

import com.conversorAlura.co.libreria.Conversion;
import com.conversorAlura.co.libreria.realizarLlamadoPag;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author carolina
 */
public class ConversorMoneda extends javax.swing.JPanel {
  
    String valorIngresado;
    
    public ConversorMoneda() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        listaDivisa1 = new javax.swing.JComboBox<>();
        listaDivisa2 = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        resultadoLabel = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        resultadoLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setLayout(null);

        content.setLayout(null);

        tittle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tittle.setText("CONVERSOR DE MONEDAS ALURA");
        content.add(tittle);
        tittle.setBounds(150, 40, 312, 22);

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Ingrese el valor y divisa a convertir: ");
        content.add(text);
        text.setBounds(150, 150, 312, 16);

        listaDivisa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP", "EUR", "USD", "JPY", "GBP", "KRW" }));
        content.add(listaDivisa1);
        listaDivisa1.setBounds(150, 180, 72, 22);

        listaDivisa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP", "EUR", "USD", "JPY", "GBP", "KRW" }));
        content.add(listaDivisa2);
        listaDivisa2.setBounds(390, 180, 72, 22);

        changeButton.setText("jButton1");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        content.add(changeButton);
        changeButton.setBounds(260, 180, 99, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        content.add(jPanel1);
        jPanel1.setBounds(200, 360, 220, 30);

        valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorActionPerformed(evt);
            }
        });
        content.add(valor);
        valor.setBounds(200, 220, 210, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setToolTipText("");
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        resultadoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultadoLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        content.add(jPanel3);
        jPanel3.setBounds(200, 420, 220, 30);

        jButton3.setText("Convertir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3);
        jButton3.setBounds(260, 270, 97, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total cambio:  ");
        content.add(jLabel5);
        jLabel5.setBounds(160, 400, 312, 16);

        jButton4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton4.setText("Conversores");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        content.add(jButton4);
        jButton4.setBounds(10, 461, 120, 30);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tasa de cambio:  ");
        content.add(jLabel6);
        jLabel6.setBounds(160, 340, 312, 16);

        add(content);
        content.setBounds(0, 0, 600, 500);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        realizarLlamadoPag Pag5 = new realizarLlamadoPag();
        BotonesIniciales conv5 = new BotonesIniciales();
        Pag5.Llamado(conv5, content);
    }//GEN-LAST:event_jButton4MouseClicked

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
              String selectedDivisa1Index = (String) listaDivisa1.getSelectedItem();
              String selectedDivisa2Index = (String) listaDivisa2.getSelectedItem();
              

              // Realizar la conversión y asignar el resultado al JLabel de resultados
              Conversion valoresFinales = new Conversion(); // OJO - Implementa la lógica de conversión
              String valorExchange1 = valoresFinales.valorExchange (selectedDivisa1Index, selectedDivisa2Index);
              resultadoLabel.setText(valorExchange1); // Actualizar el texto del JLabel
            
              try{
              valorIngresado = valor.getText();
              double valorIngresadoDouble = Double.parseDouble(valorIngresado);
              double cambio =  Double.parseDouble(valorExchange1);
              String resultado = valoresFinales.resultadoConversion(valorIngresadoDouble, cambio);
              resultadoLabel2.setText(resultado);
               } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error en caso de que el valor ingresado no sea numérico
               JOptionPane.showMessageDialog(content, "Ingresa un valor numérico válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
              
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        // TODO add your handling code here:
              int selectedDivisa1Index = listaDivisa1.getSelectedIndex();
              int selectedDivisa2Index = listaDivisa2.getSelectedIndex();
              
              listaDivisa1.setSelectedIndex(selectedDivisa2Index);
              listaDivisa2.setSelectedIndex(selectedDivisa1Index);
              
              String savedResultadoLabel2 = resultadoLabel2.getText();
              
              double validationLabel = Double.parseDouble(savedResultadoLabel2);
              if (validationLabel != 0){
                 String savedValorIngresado = valor.getText();
                 
                 resultadoLabel2.setText(savedValorIngresado);
                 valor.setText(savedResultadoLabel2);
              }
    }//GEN-LAST:event_changeButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> listaDivisa1;
    private javax.swing.JComboBox<String> listaDivisa2;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JLabel resultadoLabel2;
    private javax.swing.JLabel text;
    private javax.swing.JLabel tittle;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
